site :opscode
cookbook 'apt'
cookbook 'sudo'
cookbook 'mysql'
cookbook 'nginx'
cookbook 'git'
cookbook 'zsh'
cookbook 'vim'
cookbook 'tmux'
cookbook 'ruby_build'
cookbook 'rbenv', github: 'fnichol/chef-rbenv'
